apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "application.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: # Portmapping vom konfigurierten ServicePort zum Applikations-Port, hier 8080
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector: # definiert für welche Deployments ein LoadBalancer aufgebaut wird
    app.kubernetes.io/name: {{ include "application.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}